name: build on pullrequest close

on:
  pull_request:
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repository
        uses: actions/checkout@v3  
      - name: setup qemu  
        uses: docker/setup-qemu-action@v1
      - name: setup docker
        uses: docker/setup-buildx-action@v1
      - name: login docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/exopytongitactions:latest