name: tests
on: push
  branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get Repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test with pytest
      run: pytest
    - name: Check on failures
      if:  ${{ failure() }}
        # run: echo " "
      uses: dacbd/create-issue-action@main
      with:
          token: ${{ github.token }}
          title: action workflow failed.
          body: |
            
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
            Workflow name - `${{ github.workflow }}`
            Job -`${{ github.job }}` : status -`${{ job.status }}`
          assignees: Nom de celui qui a commit ${{ github.event.pusher.name }}