name: Run test
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name : Install deps
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Check on fail
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Action workflow failed.
          body: |
            ### Context
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
            Workflow name - `${{ github.workflow }}`
            Job -`${{ github.job }}`: status -`${{ job.status }}`
          assignees: ${{ github.event.pusher.name }}